TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../src/tt_um_byron.v ../src/alu_8bit.v ../src/carry_lookahead_adder_8bit.v
TOPLEVEL = tt_um_byron
MODULE = user_module_tb

include $(shell cocotb-config --makefiles)/Makefile.sim
